// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Alsofer.FluxoCaixa.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230427173314_MigrationInicial")]
    partial class MigrationInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Alsofer.FluxoCaixa.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<bool>("ativo")
                        .HasColumnType("bit");

                    b.Property<string>("cpfCnpj")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ddd")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("dtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtCadastro")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nmUsuarioAlteracao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nmUsuarioCadastro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeCliente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Alsofer.FluxoCaixa.Domain.Entities.ContasPagar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("descricaoContaPagar")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("dtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtCadastro")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("dtPagamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idDespesa")
                        .HasColumnType("int");

                    b.Property<int>("idFornecedor")
                        .HasColumnType("int");

                    b.Property<int>("idStatus")
                        .HasColumnType("int");

                    b.Property<string>("nmUsuarioAlteracao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nmUsuarioCadastro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("vlPagamento")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("ContasPagar");
                });

            modelBuilder.Entity("Alsofer.FluxoCaixa.Domain.Entities.ContasReceber", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("descricaoContasReceber")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("dtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtCadastro")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("dtPagamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idCliente")
                        .HasColumnType("int");

                    b.Property<int>("idDespesa")
                        .HasColumnType("int");

                    b.Property<int>("idStatus")
                        .HasColumnType("int");

                    b.Property<string>("nmUsuarioAlteracao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nmUsuarioCadastro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("vlPagamento")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("ContasReceber");
                });

            modelBuilder.Entity("Alsofer.FluxoCaixa.Domain.Entities.Despesa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<bool>("ativo")
                        .HasColumnType("bit");

                    b.Property<string>("descricaoDespesa")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("dtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtCadastro")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("nmUsuarioAlteracao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nmUsuarioCadastro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeDespesa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Despesa");
                });

            modelBuilder.Entity("Alsofer.FluxoCaixa.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<bool>("ativo")
                        .HasColumnType("bit");

                    b.Property<string>("cpfCnpj")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ddd")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("dtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtCadastro")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nmUsuarioAlteracao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nmUsuarioCadastro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeFantasia")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("razaoSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("id");

                    b.ToTable("Fornecedor");
                });

            modelBuilder.Entity("Alsofer.FluxoCaixa.Domain.Entities.Login", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<bool?>("ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("dtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nmUsuarioAlteracao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nmUsuarioCadastro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("Alsofer.FluxoCaixa.Domain.Entities.Receita", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<bool>("ativo")
                        .HasColumnType("bit");

                    b.Property<string>("descricaoReceita")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("dtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtCadastro")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("nmUsuarioAlteracao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nmUsuarioCadastro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeReceita")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Receita");
                });

            modelBuilder.Entity("Alsofer.FluxoCaixa.Domain.Entities.Status", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<bool?>("ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("dtAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("nmUsuarioAlteracao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nmUsuarioCadastro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
